---
- name: Check if Custom01 profile exixts
  shell: /opt/IBM/WebSphere/AppServer/bin/manageprofiles.sh -listProfiles | grep Custom01
  register: result
  check_mode: no
  failed_when: False
  changed_when: result.rc != 0
- name: Create Custom01 profile
  shell: |
    rm -rf /opt/IBM/WebSphere/AppServer/profiles/Custom01 && \
    /opt/IBM/WebSphere/AppServer/bin/manageprofiles.sh -create \
      -profileName Custom01 \
      -profilePath /opt/IBM/WebSphere/AppServer/profiles/Custom01 \
      -templatePath /opt/IBM/WebSphere/AppServer/profileTemplates/managed \
      -dmgrHost 192.168.33.41 \
      -dmgrPort 8879 \
      -dmgrAdminUserName wasadmin \
      -dmgrAdminPassword wasadmin
  when: result is changed
  register: result
  failed_when: result.rc not in [0, 2]
- name: Check if nodeagent started
  shell: ps -ef | grep -v grep | grep java | grep nodeagent
  register: result
  check_mode: no
  failed_when: False
  changed_when: result.rc != 0
- name: Start nodeagent
  shell: /opt/IBM/WebSphere/AppServer/profiles/Custom01/bin/startNode.sh
  when: result is changed
